version: "2"

services:
  mqtt:
    container_name: emqx
    image: emqx:latest # no config required
    ports:
      - 1883:1883
      - 18083:18083

  ha:
    container_name: hass
    image: ghcr.io/home-assistant/home-assistant:stable
    ports:
      - 8123:8123
